import jsPDF from "jspdf";

export function generateEventReportPDF(event: {
  title: string;
  date: string;
  sector: string;
  location: string;
  status: string;
  severity: string;
  desc: string;
}) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Header bar
  doc.setFillColor(17, 24, 39);
  doc.rect(0, 0, pageWidth, 40, "F");
  doc.setFillColor(16, 185, 129);
  doc.rect(0, 40, pageWidth, 2, "F");

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(255, 255, 255);
  doc.text("INTELLISECTOR", 14, y);
  y += 8;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(156, 163, 175);
  doc.text("Executive Event Intelligence Report", 14, y);

  // Timestamp
  doc.setFontSize(8);
  doc.text(`Generated: ${new Date().toLocaleString()}`, pageWidth - 14, 20, { align: "right" });
  doc.text("CLASSIFIED — INTERNAL USE ONLY", pageWidth - 14, 28, { align: "right" });

  y = 52;

  // Event Title
  doc.setTextColor(31, 41, 55);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  const titleLines = doc.splitTextToSize(event.title, pageWidth - 28);
  doc.text(titleLines, 14, y);
  y += titleLines.length * 7 + 6;

  // Metadata table
  doc.setDrawColor(229, 231, 235);
  doc.setFillColor(249, 250, 251);
  doc.rect(14, y, pageWidth - 28, 32, "FD");

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(107, 114, 128);

  const col1 = 20;
  const col2 = pageWidth / 2 + 10;
  const rowH = 14;

  doc.text("Date", col1, y + 10);
  doc.text("Sector", col2, y + 10);
  doc.text("Location", col1, y + 10 + rowH);
  doc.text("Severity", col2, y + 10 + rowH);

  doc.setFont("helvetica", "bold");
  doc.setTextColor(31, 41, 55);
  doc.text(event.date, col1 + 30, y + 10);
  doc.text(event.sector, col2 + 30, y + 10);
  doc.text(event.location, col1 + 30, y + 10 + rowH);
  doc.text(event.severity, col2 + 30, y + 10 + rowH);

  y += 42;

  // Status badge
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  if (event.status === "Upcoming") {
    doc.setFillColor(16, 185, 129);
    doc.setTextColor(255, 255, 255);
  } else {
    doc.setFillColor(59, 130, 246);
    doc.setTextColor(255, 255, 255);
  }
  const statusText = `STATUS: ${event.status.toUpperCase()}`;
  doc.roundedRect(14, y, 50, 8, 2, 2, "F");
  doc.text(statusText, 18, y + 5.5);
  y += 16;

  // Executive Summary section
  doc.setFillColor(16, 185, 129);
  doc.rect(14, y, 3, 14, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(31, 41, 55);
  doc.text("EXECUTIVE SUMMARY", 22, y + 5);
  y += 18;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(55, 65, 81);
  const descLines = doc.splitTextToSize(event.desc, pageWidth - 28);
  doc.text(descLines, 14, y);
  y += descLines.length * 5 + 10;

  // AI Risk Assessment section
  doc.setFillColor(245, 158, 11);
  doc.rect(14, y, 3, 14, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(31, 41, 55);
  doc.text("AI RISK ASSESSMENT", 22, y + 5);
  y += 18;

  const riskText = event.status === "Completed"
    ? "Event has concluded. Post-event structural analysis indicates standard market absorption with no critical supply chain disruptions. No immediate action required."
    : "Upcoming event requires active monitoring. High probability of localized logistics impact and short-term volatility in respective sector indexes. Recommend pre-positioning hedging strategies.";

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(55, 65, 81);
  const riskLines = doc.splitTextToSize(riskText, pageWidth - 28);
  doc.text(riskLines, 14, y);
  y += riskLines.length * 5 + 14;

  // Footer
  doc.setDrawColor(229, 231, 235);
  doc.line(14, y, pageWidth - 14, y);
  y += 8;
  doc.setFontSize(7);
  doc.setTextColor(156, 163, 175);
  doc.text("This report is auto-generated by IntelliSector AI Intelligence Engine. For internal distribution only.", 14, y);
  doc.text(`Page 1 of 1`, pageWidth - 14, y, { align: "right" });

  doc.save(`Event_Report_${event.title.replace(/\s+/g, "_").substring(0, 20)}.pdf`);
}

export function generateTenderDossierPDF(tender: {
  id: string;
  title: string;
  issuer: string;
  sector: string;
  value: string;
  region: string;
  status: string;
  deadline: string;
  matchScore: string;
}) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Header bar
  doc.setFillColor(17, 24, 39);
  doc.rect(0, 0, pageWidth, 40, "F");
  doc.setFillColor(229, 169, 60);
  doc.rect(0, 40, pageWidth, 2, "F");

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(255, 255, 255);
  doc.text("INTELLISECTOR", 14, y);
  y += 8;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(156, 163, 175);
  doc.text("Tender Intelligence Dossier", 14, y);

  // Timestamp & classification
  doc.setFontSize(8);
  doc.text(`Generated: ${new Date().toLocaleString()}`, pageWidth - 14, 20, { align: "right" });
  doc.text("CONFIDENTIAL — STRATEGIC PROCUREMENT", pageWidth - 14, 28, { align: "right" });

  y = 52;

  // Tender ID Badge
  doc.setFillColor(229, 169, 60);
  doc.roundedRect(14, y - 6, 36, 10, 2, 2, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255);
  doc.text(tender.id, 18, y + 1);

  y += 12;

  // Tender Title
  doc.setTextColor(31, 41, 55);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  const titleLines = doc.splitTextToSize(tender.title, pageWidth - 28);
  doc.text(titleLines, 14, y);
  y += titleLines.length * 7 + 8;

  // Metadata table
  doc.setDrawColor(229, 231, 235);
  doc.setFillColor(249, 250, 251);
  doc.rect(14, y, pageWidth - 28, 46, "FD");

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(107, 114, 128);

  const col1 = 20;
  const col2 = pageWidth / 2 + 10;
  const rowH = 14;

  doc.text("Issuer", col1, y + 10);
  doc.text("Sector", col2, y + 10);
  doc.text("Est. Value", col1, y + 10 + rowH);
  doc.text("Region", col2, y + 10 + rowH);
  doc.text("Deadline", col1, y + 10 + rowH * 2);
  doc.text("Status", col2, y + 10 + rowH * 2);

  doc.setFont("helvetica", "bold");
  doc.setTextColor(31, 41, 55);
  doc.text(tender.issuer, col1 + 35, y + 10);
  doc.text(tender.sector, col2 + 35, y + 10);
  doc.text(tender.value, col1 + 35, y + 10 + rowH);
  doc.text(tender.region, col2 + 35, y + 10 + rowH);
  doc.text(tender.deadline, col1 + 35, y + 10 + rowH * 2);
  doc.text(tender.status, col2 + 35, y + 10 + rowH * 2);

  y += 56;

  // Match Score highlight
  doc.setFillColor(16, 185, 129);
  doc.roundedRect(14, y, pageWidth - 28, 18, 3, 3, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(255, 255, 255);
  doc.text(`AI STRATEGIC MATCH SCORE: ${tender.matchScore}`, pageWidth / 2, y + 12, { align: "center" });
  y += 28;

  // Analysis section
  doc.setFillColor(229, 169, 60);
  doc.rect(14, y, 3, 14, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(31, 41, 55);
  doc.text("STRATEGIC ANALYSIS", 22, y + 5);
  y += 18;

  const analysisText = `This tender opportunity issued by ${tender.issuer} for operations in the ${tender.region} represents a significant procurement event in the ${tender.sector} vertical. The estimated contract value of ${tender.value} places this among the high-priority opportunities currently tracked by the IntelliSector intelligence engine.\n\nOur AI analysis engine assigns your firm a ${tender.matchScore} match score for this opportunity, indicating strong alignment with your operational capabilities, geographic footprint, and recent project portfolio. The current status is "${tender.status}" with a deadline of ${tender.deadline}.`;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(55, 65, 81);
  const analysisLines = doc.splitTextToSize(analysisText, pageWidth - 28);
  doc.text(analysisLines, 14, y);
  y += analysisLines.length * 5 + 10;

  // Recommendation
  doc.setFillColor(16, 185, 129);
  doc.rect(14, y, 3, 14, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(31, 41, 55);
  doc.text("RECOMMENDATION", 22, y + 5);
  y += 18;

  const recText = tender.status === "Open"
    ? "HIGH PRIORITY — Initiate bid preparation immediately. Recommend assembling cross-functional bid team and scheduling site reconnaissance within 48 hours."
    : tender.status === "Awarded"
    ? "MONITORING — Contract has been awarded. Track for sub-contracting opportunities and future phase expansions."
    : "ACTIVE EVALUATION — Tender is under review. Maintain documentation readiness and prepare technical qualification responses.";

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(55, 65, 81);
  const recLines = doc.splitTextToSize(recText, pageWidth - 28);
  doc.text(recLines, 14, y);
  y += recLines.length * 5 + 14;

  // Footer
  doc.setDrawColor(229, 231, 235);
  doc.line(14, y, pageWidth - 14, y);
  y += 8;
  doc.setFontSize(7);
  doc.setTextColor(156, 163, 175);
  doc.text("This dossier is auto-generated by IntelliSector AI Intelligence Engine. Confidential — Strategic Procurement.", 14, y);
  doc.text(`Page 1 of 1`, pageWidth - 14, y, { align: "right" });

  doc.save(`Tender_Dossier_${tender.id}.pdf`);
}
